'use strict';
const STORAGE_KEY='homebound_journey_v1';
const defaults={stepsCloser:287,recoveryDismissed:false,lastBackup:null,milestones:[
{id:'home-deposit',icon:'🏡',publicName:'Home Deposit',accountName:'House Deposit',starting:60000,balance:18500,interest:0,minPayment:500,extraPayment:0,frequency:'month',due:'2026-08-14',why:'Every dollar here brings your future home a little closer.',payments:[]},
{id:'car-loan',icon:'🚗',publicName:'Car Loan',accountName:'Mahindra XUV700',starting:14500,balance:8240,interest:6.25,minPayment:320,extraPayment:120,frequency:'week',due:'2026-08-21',why:'Each payment means more freedom and one step closer to owning your Mahindra outright.',payments:[{date:'2026-08-01',amount:440,type:'Minimum + extra'}]},
{id:'trip',icon:'✈️',publicName:'Europe Trip',accountName:'Next Trip',starting:5000,balance:3650,interest:0,minPayment:150,extraPayment:0,frequency:'month',due:'2026-09-05',why:'Small savings today become unforgettable memories tomorrow.',payments:[]},
{id:'emergency',icon:'🛡️',publicName:'Emergency Fund',accountName:'Emergency Fund',starting:6300,balance:1200,interest:0,minPayment:250,extraPayment:0,frequency:'month',due:'2026-08-10',why:'This safety net protects your plans when life is unpredictable.',payments:[]}
]};
let state=load();let activeTab='home';let selectedMilestone=null;let activeSheetTab='overview';
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(Number(n)||0);
const pct=m=>Math.max(0,Math.min(100,((m.starting-m.balance)/m.starting)*100||0));
function totals(){const starting=state.milestones.reduce((s,m)=>s+m.starting,0),left=state.milestones.reduce((s,m)=>s+m.balance,0);return{starting,left,cleared:starting-left,percent:starting?((starting-left)/starting)*100:0}}
function greeting(){const now=new Date(),h=now.getHours();document.getElementById('greetingTitle').textContent=`${h<12?'Good morning':h<18?'Good afternoon':'Good evening'} ${h<12?'☀️':h<18?'🌤️':'🌙'}`;document.getElementById('todayLabel').textContent=new Intl.DateTimeFormat('en-AU',{weekday:'long',day:'numeric',month:'long'}).format(now)}
function render(){const t=totals();document.getElementById('stepsCloser').textContent=state.stepsCloser;document.getElementById('journeyPercent').textContent=`${t.percent.toFixed(1)}%`;document.getElementById('journeyBar').style.setProperty('--progress',`${t.percent}%`);document.getElementById('recoveryBanner').hidden=state.recoveryDismissed;const next=state.milestones.find(m=>m.balance>0)||state.milestones[0];document.getElementById('homeNextStopName').textContent=next.publicName;document.getElementById('homeNextStopDue').textContent=`${money(next.balance)} left`;document.getElementById('overallJourneyPercent').textContent=`${t.percent.toFixed(1)}%`;document.getElementById('ringPercent').textContent=`${t.percent.toFixed(0)}%`;document.getElementById('summaryRing').style.setProperty('--ring',`${t.percent}%`);document.getElementById('totalStarting').textContent=money(t.starting);document.getElementById('totalCleared').textContent=money(t.cleared);document.getElementById('totalLeft').textContent=money(t.left);renderMap()}
function renderMap(){const map=document.getElementById('milestoneMap');map.innerHTML='<div class="map-start"><span>🏁</span><div><strong>Start</strong><br><small>Your journey begins</small></div></div>'+state.milestones.map(m=>{const p=pct(m),completed=m.balance<=0,attention=!completed&&m.due&&new Date(m.due)<new Date(Date.now()+7*86400000);return `<button class="milestone-card ${completed?'completed':attention?'attention':''}" data-milestone="${m.id}"><span class="milestone-icon">${m.icon}</span><span class="milestone-copy"><span class="milestone-title-row"><strong>${m.publicName}</strong><i class="milestone-status-dot"></i></span><b>${p.toFixed(0)}%</b><span class="bar"><i style="--progress:${p}%"></i></span><small>${completed?'Completed':money(m.balance)+' left'}</small></span><span class="milestone-next"><small>${completed?'Well done':'Next payment'}</small><b>${completed?'🎉':formatDate(m.due)}</b><span class="chev">›</span></span></button>`}).join('')+'<div class="map-finish"><span>🏆</span><div><strong>Freedom</strong><br><small>The best is yet to come.</small></div></div>'}
function formatDate(v){if(!v)return'Not set';return new Intl.DateTimeFormat('en-AU',{day:'2-digit',month:'short'}).format(new Date(v+'T00:00:00'))}
function switchTab(tab){if(!['home','journey'].includes(tab)){openSheet(['🔒','Coming next','This tab will be designed after Journey is approved.','']);return}activeTab=tab;document.getElementById('homePage').hidden=tab!=='home';document.getElementById('journeyPage').hidden=tab!=='journey';document.getElementById('homePage').classList.toggle('active-page',tab==='home');document.getElementById('journeyPage').classList.toggle('active-page',tab==='journey');document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});window.scrollTo({top:0,behavior:'smooth'})}
function openSheet(d){document.getElementById('sheetIcon').textContent=d[0];document.getElementById('sheetTitle').textContent=d[1];document.getElementById('sheetDescription').textContent=d[2]||'';document.getElementById('sheetContent').innerHTML=d[3]||'';document.getElementById('detailSheet').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeSheet(id='detailSheet'){document.getElementById(id).setAttribute('aria-hidden','true');document.body.style.overflow=''}
const homeDetails={today:['☀️','Today’s focus','A calm overview of what matters next.',''], 'next-stop':['📍','Next Stop','Your next financial milestone.',`<div class="detail-block"><strong>${state.milestones[0].publicName}</strong><span>${money(state.milestones[0].balance)} left to go.</span></div>`], 'next-adventure':['🌊','Next Adventure','The next experience you are looking forward to together.','<div class="detail-block"><strong>Esperance</strong><span>103 days to go.</span></div>'],garden:['🌳','Garden','Your savings and net worth represented as something beautiful growing.',''],dreams:['⭐','Dreams','Your shared vision board.',''],memories:['📖','Memories','Your shared timeline of photos, trips and milestones.',''],wins:['🏆','Wins','Celebrate every meaningful achievement.',''],adventures:['🧭','Adventures','Plan your next trip and preserve completed journeys.','']};
function milestoneSheet(id,tab='overview'){selectedMilestone=state.milestones.find(m=>m.id===id);if(!selectedMilestone)return;activeSheetTab=tab;const m=selectedMilestone,p=pct(m);const tabs=`<div class="sheet-tabs">${['overview','payments','plan','notes'].map(x=>`<button data-sheet-tab="${x}" class="${x===tab?'active':''}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div>`;let body='';if(tab==='overview')body=`<div class="finance-grid"><div class="finance-stat"><small>Current balance</small><strong>${money(m.balance)}</strong></div><div class="finance-stat"><small>Starting balance</small><strong>${money(m.starting)}</strong></div><div class="finance-stat"><small>Interest rate</small><strong>${m.interest.toFixed(2)}% p.a.</strong></div><div class="finance-stat"><small>Estimated payoff</small><strong>${estimatePayoff(m)}</strong></div><div class="finance-stat"><small>Minimum payment</small><strong>${money(m.minPayment)} / ${m.frequency}</strong></div><div class="finance-stat"><small>Extra payment</small><strong>${money(m.extraPayment)} / ${m.frequency}</strong></div></div><div class="detail-block"><strong>💡 Why it matters</strong><span>${m.why}</span></div><button class="primary-button" data-add-payment="${m.id}">Make a payment</button>`;if(tab==='payments')body=`<div class="payment-list">${m.payments.length?m.payments.slice().reverse().map(x=>`<div class="payment-row"><span>${new Intl.DateTimeFormat('en-AU').format(new Date(x.date))}<br><small>${x.type||'Payment'}</small></span><b>${money(x.amount)}</b></div>`).join(''):'<div class="detail-block"><strong>No payments yet</strong><span>Your payment history will appear here.</span></div>'}</div><button class="secondary-button" data-add-payment="${m.id}">＋ Add payment</button>`;if(tab==='plan')body=`<div class="form-grid"><label>Extra payment<input id="whatIfExtra" type="number" min="0" value="${m.extraPayment||100}"></label><label>Frequency<select id="whatIfFrequency"><option value="week">per week</option><option value="month">per month</option></select></label><button class="primary-button" data-calc-plan="${m.id}">Calculate impact</button></div><div id="planResult"></div>`;if(tab==='notes')body=`<div class="detail-block"><strong>Why it matters</strong><span>${m.why}</span></div><button class="secondary-button" data-edit-milestone="${m.id}">Edit milestone</button>`;openSheet([m.icon,m.publicName,`${p.toFixed(0)}% complete • ${money(m.balance)} left`,tabs+body])}
function estimatePayoff(m,extra=m.extraPayment){const payment=(m.minPayment+extra)*(m.frequency==='week'?52/12:1);if(payment<=0)return'Not set';const months=Math.ceil(m.balance/payment);const d=new Date();d.setMonth(d.getMonth()+months);return new Intl.DateTimeFormat('en-AU',{month:'short',year:'numeric'}).format(d)}
function paymentForm(id){const m=state.milestones.find(x=>x.id===id);openSheet([m.icon,`Pay ${m.publicName}`,'Record a payment and update your progress.',`<form id="paymentForm" class="form-grid"><input type="hidden" name="id" value="${m.id}"><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Date<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Type<select name="type"><option>Minimum payment</option><option>Extra payment</option><option>Minimum + extra</option></select></label><button class="primary-button" type="submit">Save payment</button></form>`])}
function addMilestoneForm(){openSheet(['＋','New milestone','Add another step to your roadmap.',`<form id="milestoneForm" class="form-grid"><label>Emoji<input name="icon" value="🎯" maxlength="4"></label><label>Milestone name<input name="publicName" required placeholder="New milestone"></label><label>Starting amount<input name="starting" type="number" min="1" required></label><label>Current balance<input name="balance" type="number" min="0" required></label><label>Interest rate %<input name="interest" type="number" step="0.01" value="0"></label><label>Minimum payment<input name="minPayment" type="number" min="0" value="0"></label><label>Payment frequency<select name="frequency"><option value="month">Monthly</option><option value="week">Weekly</option></select></label><label>Next due date<input name="due" type="date"></label><label>Why it matters<textarea name="why" placeholder="What will this milestone change for your family?"></textarea></label><button class="primary-button" type="submit">Add to journey</button></form>`])}
function exportBackup(){const blob=new Blob([JSON.stringify({version:4,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`homebound-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);state.lastBackup=new Date().toISOString();save();toast('💾 Backup created')}
function toast(text){let t=document.querySelector('.success-toast');if(!t){t=document.createElement('div');t.className='success-toast';document.body.append(t)}t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){switchTab(tab.dataset.tab);return}const detail=e.target.closest('[data-detail]');if(detail)openSheet(homeDetails[detail.dataset.detail]);const milestone=e.target.closest('[data-milestone]');if(milestone)milestoneSheet(milestone.dataset.milestone);const st=e.target.closest('[data-sheet-tab]');if(st&&selectedMilestone)milestoneSheet(selectedMilestone.id,st.dataset.sheetTab);const pay=e.target.closest('[data-add-payment]');if(pay)paymentForm(pay.dataset.addPayment);if(e.target.closest('[data-calc-plan]')){const extra=Number(document.getElementById('whatIfExtra').value||0),m=state.milestones.find(x=>x.id===e.target.closest('[data-calc-plan]').dataset.calcPlan),current=estimatePayoff(m,0),planned=estimatePayoff(m,extra);document.getElementById('planResult').innerHTML=`<div class="calc-result"><div><small>Current payoff</small><strong>${current}</strong></div><div><small>With extra payment</small><strong>${planned}</strong></div></div>`}const action=e.target.closest('[data-action]');if(action){if(action.dataset.action==='backup')exportBackup();else if(action.dataset.action==='payment')paymentForm(state.milestones.find(m=>m.balance>0).id);else openSheet([action.dataset.action==='memory'?'📷':'⭐',action.dataset.action==='memory'?'Add a memory':'Add a dream','This feature comes after Journey approval.',''])}if(e.target.closest('[data-close-sheet]'))closeSheet();if(e.target.closest('[data-close-notifications]'))closeSheet('notificationsSheet')});
document.addEventListener('submit',e=>{if(e.target.id==='paymentForm'){e.preventDefault();const fd=new FormData(e.target),m=state.milestones.find(x=>x.id===fd.get('id')),amount=Number(fd.get('amount'));m.balance=Math.max(0,m.balance-amount);m.payments.push({amount,date:fd.get('date'),type:fd.get('type')});state.stepsCloser++;save();render();closeSheet();toast('🎉 Another step closer to home')}if(e.target.id==='milestoneForm'){e.preventDefault();const fd=new FormData(e.target),starting=Number(fd.get('starting')),balance=Number(fd.get('balance'));state.milestones.push({id:'m-'+Date.now(),icon:fd.get('icon')||'🎯',publicName:fd.get('publicName'),accountName:fd.get('publicName'),starting,balance,interest:Number(fd.get('interest')||0),minPayment:Number(fd.get('minPayment')||0),extraPayment:0,frequency:fd.get('frequency'),due:fd.get('due'),why:fd.get('why')||'A meaningful step on your road home.',payments:[]});save();render();closeSheet();toast('Milestone added') }});
document.getElementById('addMilestoneButton').addEventListener('click',addMilestoneForm);document.getElementById('notificationsButton').addEventListener('click',()=>{document.getElementById('notificationsSheet').setAttribute('aria-hidden','false');document.getElementById('notificationBadge').hidden=true;document.body.style.overflow='hidden'});document.getElementById('dismissRecovery').addEventListener('click',()=>{state.recoveryDismissed=true;save();render()});const carousel=document.getElementById('lifeCarousel'),dots=[...document.querySelectorAll('.carousel-dots i')];carousel.addEventListener('scroll',()=>{const max=Math.max(1,carousel.scrollWidth-carousel.clientWidth),index=Math.min(dots.length-1,Math.round((carousel.scrollLeft/max)*(dots.length-1)));dots.forEach((d,i)=>d.classList.toggle('active',i===index))},{passive:true});
greeting();render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
