'use strict';
const STORAGE_KEY='homebound_home_approved_v3';
const defaults={stepsCloser:287,journeyPercent:10.2,recoveryDismissed:false,lastBackup:null};
let state=load();
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return{...defaults}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function greeting(){const now=new Date(),h=now.getHours();const word=h<12?'Good morning':h<18?'Good afternoon':'Good evening';document.getElementById('greetingTitle').textContent=`${word} ${h<12?'☀️':h<18?'🌤️':'🌙'}`;document.getElementById('todayLabel').textContent=new Intl.DateTimeFormat('en-AU',{weekday:'long',day:'numeric',month:'long'}).format(now)}
function render(){document.getElementById('stepsCloser').textContent=state.stepsCloser;document.getElementById('journeyPercent').textContent=`${state.journeyPercent.toFixed(1)}%`;document.getElementById('recoveryBanner').hidden=state.recoveryDismissed}
const details={
  today:['☀️','Today’s focus','A calm overview of the two things that matter next.','<div class="detail-block"><strong>📍 Next Stop</strong><span>Weekend getaway • due in 2 days.</span></div><div class="detail-block"><strong>🌊 Next Adventure</strong><span>Esperance • 103 days to go.</span></div>'],
  'next-stop':['📍','Next Stop','Your next gentle milestone on the road home.','<div class="detail-block"><strong>Weekend getaway</strong><span>Planned for two days from now. Reminders and private financial details will connect after Home is approved.</span></div>'],
  'next-adventure':['🌊','Next Adventure','The next experience you are looking forward to together.','<div class="detail-block"><strong>Esperance</strong><span>103 days to go. The full Adventures tab will later hold planning, budget and memories.</span></div>'],
  journey:['🚗','Journey','Your progress towards freedom, shown without stressful account names.','<div class="detail-block"><strong>10.2% complete</strong><span>Tap through later to see scenic destinations and the real account details privately.</span></div>'],
  garden:['🌳','Garden','Your savings and net worth represented as something beautiful growing.','<div class="detail-block"><strong>Growing 🌱</strong><span>Savings Grove, Home Path and other zones will explain exactly what they represent.</span></div>'],
  dreams:['⭐','Dreams','Your shared vision board.','<div class="detail-block"><strong>6 active dreams</strong><span>Dream Home, Mini Cooper, Next Trip and more.</span></div>'],
  memories:['📖','Memories','Your shared timeline of photos, trips and milestones.','<div class="detail-block"><strong>42 moments</strong><span>Photos will be compressed and stored locally on your phone.</span></div>'],
  wins:['🏆','Wins','A place to celebrate every meaningful achievement.','<div class="detail-block"><strong>Celebrate progress</strong><span>Financial, travel, relationship and personal wins will all live here.</span></div>'],
  adventures:['🧭','Adventures','Plan your next trip and preserve completed journeys.','<div class="detail-block"><strong>New places await</strong><span>Passport stamps, itinerary, budget and memories will come later.</span></div>']
};
function openSheet(key){const d=Array.isArray(key)?key:details[key];if(!d)return;document.getElementById('sheetIcon').textContent=d[0];document.getElementById('sheetTitle').textContent=d[1];document.getElementById('sheetDescription').textContent=d[2];document.getElementById('sheetContent').innerHTML=d[3]||'';document.getElementById('detailSheet').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeSheet(id='detailSheet'){document.getElementById(id).setAttribute('aria-hidden','true');document.body.style.overflow=''}
function exportBackup(){const payload={version:3,exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`homebound-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);state.lastBackup=new Date().toISOString();save();openSheet(['💾','Backup created','Your Homebound data has been exported.','<div class="detail-block"><strong>Keep it safe</strong><span>Save the file to iCloud Drive, Google Drive or another trusted place.</span></div>'])}
function quick(action){if(action==='backup')return exportBackup();if(action==='payment'){openSheet(['＋','Add a payment','Record a small step forward.','<button class="primary-button" id="demoPayment">Record demo progress</button>']);setTimeout(()=>document.getElementById('demoPayment')?.addEventListener('click',()=>{state.stepsCloser++;state.journeyPercent=Math.min(100,state.journeyPercent+.1);save();render();closeSheet()}));return}const map={memory:['📷','Add a memory','Save a meaningful moment.','<div class="detail-block"><strong>Coming after Home approval</strong><span>The full form will support a photo, caption and date.</span></div>'],dream:['⭐','Add a dream','Give your next dream a place to grow.','<div class="detail-block"><strong>Coming after Home approval</strong><span>The full form will include a target, date, checklist and notes.</span></div>']};openSheet(map[action])}
document.addEventListener('click',e=>{const d=e.target.closest('[data-detail]');if(d)openSheet(d.dataset.detail);const a=e.target.closest('[data-action]');if(a)quick(a.dataset.action);const n=e.target.closest('[data-tab]');if(n&&n.dataset.tab!=='home')openSheet(details[n.dataset.tab]||['🏡','Coming next','Home is the only implemented screen for now.','']);if(e.target.closest('[data-close-sheet]'))closeSheet();if(e.target.closest('[data-close-notifications]'))closeSheet('notificationsSheet')});
document.getElementById('notificationsButton').addEventListener('click',()=>{document.getElementById('notificationsSheet').setAttribute('aria-hidden','false');document.getElementById('notificationBadge').hidden=true;document.body.style.overflow='hidden'});
document.getElementById('dismissRecovery').addEventListener('click',()=>{state.recoveryDismissed=true;save();render()});
const carousel=document.getElementById('lifeCarousel'),dots=[...document.querySelectorAll('.carousel-dots i')];carousel.addEventListener('scroll',()=>{const max=Math.max(1,carousel.scrollWidth-carousel.clientWidth);const index=Math.min(dots.length-1,Math.round((carousel.scrollLeft/max)*(dots.length-1)));dots.forEach((d,i)=>d.classList.toggle('active',i===index))},{passive:true});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSheet();closeSheet('notificationsSheet')}});
greeting();render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
